version: "3.9"

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: planner_database
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg_bouncer:
    container_name: planner_bouncer
    build: ./pg_bouncer/
    env_file: .env
    ports:
      - "6432:6432"
    depends_on:
      - db

  redis:
    container_name: planner_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    container_name: planner_backend
    image: licrimovor/planner_backend
    entrypoint: /app/docker/backend-entrypoint.sh
    env_file: .env
    depends_on:
      - pg_bouncer
    volumes:
      - static:/backend_static
      - media:/app/backend/media
      - ./sent_emails:/app/backend/sent_emails
      - ./data:/app/data
      - ./.env:/.env

  # frontend:
  #   image: licrimovor/planner_frontend
  #   container_name: planner_frontend
  #   volumes:
  #     - static:/app

  nginx:
    container_name: planner_nginx
    image: nginx:1.22.1
    env_file: .env
    ports:
      - 7000:80
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html/frontend/dist
      - static:/usr/share/nginx/html/
      - media:/media

  worker:
    container_name: planner_worker
    image: licrimovor/planner_backend
    entrypoint: /app/docker/worker-entrypoint.sh
    env_file: .env
    depends_on:
      - backend
      - redis
    volumes:
      - ./planer:/usr/src/app
      - ./.env:/.env

  beat:
    container_name: planner_beat
    image: licrimovor/planner_backend
    entrypoint: /app/docker/beat-entrypoint.sh
    env_file: .env
    depends_on:
      - backend
      - redis
      - worker
    volumes:
      - ./planer:/usr/src/app
      - ./.env:/.env

  telegram:
    container_name: planner_telegram
    image: licrimovor/planner_backend
    command: python backend/manage.py runtelegram
    env_file: .env
    depends_on:
      - backend
      - redis
    volumes:
      - ./planer:/usr/src/app
      - ./.env:/.env
