version: "3.9"

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: planner_database
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    container_name: planner_backend
    image: licrimovor/planner_backend
    entrypoint: /app/docker/backend-entrypoint.sh
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./data:/data
      - ./.env:/.env

  # frontend:
  #   container_name: planner_frontend
  #   image: licrimovor/planner_frontend
  #   env_file: .env
  #   command: cp -r /app/static/. /static/
  #   volumes:
  #     - static:/app/static/

  nginx:
    container_name: planner_nginx
    image: nginx:1.22.1
    env_file: .env
    ports:
      - 7000:80
    depends_on:
      - backend
      # - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - media:/media

  worker:
    container_name: planner_worker
    image: licrimovor/planner_backend
    entrypoint: /app/docker/worker-entrypoint.sh
    env_file: .env
    depends_on:
      - backend
      - redis
    volumes:
      - ./planer:/usr/src/app
      - ./.env:/.env

  beat:
    container_name: planner_beat
    image: licrimovor/planner_backend
    entrypoint: /app/docker/beat-entrypoint.sh
    env_file: .env
    depends_on:
      - backend
      - redis
      - worker
    volumes:
      - ./planer:/usr/src/app
      - ./.env:/.env

  telegram:
    container_name: planner_telegram
    image: licrimovor/planner_backend
    command: python backend/manage.py runtelegram
    env_file: .env
    depends_on:
      - backend
      - redis
    volumes:
      - ./planer:/usr/src/app
      - ./.env:/.env


    mosquitto:
      container_name: MQTT_server
      image: eclipse-mosquitto
      ports:
        - 1883:1883
      volumes:
        - /root/MQTT_server/config:/mosquitto/config
        - /root/MQTT_server/data:/mosquitto/data
        - /root/MQTT_server/log:/mosquitto/log eclipse-mosquitto
